on:
    push:
        branches: 
            - main

jobs:
    test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                platforms: linux/amd64
                install: true
            
            - name: Build the Docker image
              run: |
                docker build -f ./Dockerfile -t test --secret id=test_secret,src=./secretFile --progress=plain --no-cache .
            
            - name: Run the Docker image
              run: |
                docker run -it --rm test cat /t